version: '3'
services: 
  node_app:
    container_name: node_app
    restart: always
    build: .
    ports: 
      - '4000:4000'
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
      